on: push
name: ğŸ“Œlouk test app changes
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”Get latest code
        uses: actions/checkout@v3
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: test.vache-revive.ir
          protocol: ftp
          port: 21
          username: admin_admin
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**

